tags:
    - Products
summary: Get list of Seller's Products
description: Get list of Seller's Products
parameters:
    - in: header
      name: Authorization
      schema:
          type: string
          format: JWT
          example: Bearer <JWT>
      description: JWT Token
      required: true
    - name: page
      in: query
      required: false
      schema:
          type: integer
          example: 1
      description: Page number
    - name: per_page
      in: query
      required: false
      schema:
          type: integer
          example: 10
      description: Per page
responses:
    200:
        description: Returns list of seller's products
        schema:
            type: object
            properties:
                products:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: integer
                                example: 1
                            name:
                                type: string
                                example: "name"
                            description:
                                type: string
                                example: "description"
                            price:
                                type: integer
                                example: 100
                            weight_kg:
                                type: float
                                example: 0.5
                            volume_m3:
                                type: float
                                example: 0.5
                            stock:
                                type: integer
                                example: 10
                            image_url:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                            example: 1
                                        image_public_id:
                                            type: string
                                            example: iyronmbpu5k0qxm
                                        image_secure_url:
                                            type: string
                                            example: https://res.cloudinary.com/gfp-group-1/image/upload/v1610267581/iyronmbpu5k0qxm.png
                                        product_id:
                                            type: integer
                                            example: 1
                            product_type:
                                type: integer
                                example: 1
                            category_id:
                                type: integer
                                example: 1
                            is_active:
                                type: integer
                                example: 0
                            sold_qty:
                                type: integer
                                example: 5
                            reviews:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                            example: 1
                                        product_id:
                                            type: integer
                                            example: 1
                                        seller_id:
                                            type: integer
                                            example: 1
                                        user_id:
                                            type: integer
                                            example: 1
                                        rating:
                                            type: float
                                            example: 4.5
                                        review:
                                            type: string
                                            example: "review"
                            avg_rating:
                                type: float
                                example: 4.5
                            seller_id:
                                type: integer
                                example: 1
                            created_at:
                                type: string
                                format: datetime
                                example: "2021-01-01 00:00:00"
                total_page:
                    type: integer
                    example: 1
                current_page:
                    type: integer
                    example: 1
                total_items:
                    type: integer
                    example: 1
    400:
        description: Failed to pass validation process
        schema:
            type: object
            properties:
                error:
                    type: string
                    example: Unauthorized
    500:
        description: Something wrong with the database.
        schema:
            type: object
            properties:
                error:
                    type: string
                    example: Cannot connect to the database.
